# punjabi_stemmer/stemmer.py

import os

class PunjabiStemmer:
    def __init__(self, data_dir):
        self.rules = [
            {"match": "ਪ੍ਰਰਸਤੀ", "strip": "ਪ੍ਰਰਸਤੀ", "add": ""},
{"match": "ਪੂਰਵਕ", "strip": "ਪੂਰਵਕ", "add": ""},
{"match": "ਉਿਦਆਂ", "strip": "ਉਿਦਆਂ", "add": ""},
{"match": "ਉਣੀਆਂ", "strip": "ਉਣੀਆਂ", "add": ""},
{"match": "ਅਈਆ", "strip": "ਅਈਆ", "add": ""},
{"match": "ਅਤਣ", "strip": "ਅਤਣ", "add": ""},
{"match": "ਅਹਿਰਾ", "strip": "ਅਹਿਰਾ", "add": ""},
{"match": "'ਆਕਲ", "strip": "ਆਕਲ", "add": ""},
{"match": "ਆਵਟ", "strip": "ਆਵਟ", "add": ""},
{"match": "ਆਵਣ", "strip": "ਆਵਣ", "add": ""},
{"match": "ਆਵਣੀ", "strip": "ਆਵਣੀ", "add": ""},
{"match": "ਆਵਤ", "strip": "ਆਵਤ", "add": ""},
{"match": "ਆਵਲੀ", "strip": "ਆਵਲੀ", "add": ""},
{"match": "ਆਹਟ", "strip": "ਆਹਟ", "add": ""},
{"match": "ਈਅਲ", "strip": "ਈਅਲ", "add": ""},
{"match": "ਊਗੜਾ", "strip": "ਊਗੜਾ", "add": ""},
{"match": "ਕਰਣ", "strip": "ਕਰਣ", "add": ""},
{"match": "ਕਾਰਕ", "strip": "ਕਾਰਕ", "add": ""},
{"match": "ਜਨਕ", "strip": "ਜਨਕ", "add": ""},
{"match": "ਗਰਦੀ", "strip": "ਗਰਦੀ", "add": ""},
{"match": "ਤੰਤਰ", "strip": "ਤੰਤਰ", "add": ""},      
{"match": "ਦਾਇਕ", "strip": "ਦਾਇਕ", "add": " "},
{"match": "ਦਾਰਨੀ", "strip": "ਦਾਰਨੀ", "add": " "},
{"match": "ਨਵੀਸ", "strip": "ਨਵੀਸ", "add": " "},
{"match": "ਪ੍ਰਸਤ", "strip": "ਪ੍ਰਸਤ", "add": " "},
{"match": "ਪਾਤਰ", "strip": "ਪਾਤਰ", "add": " "},
{"match": "'ਪੂਰਣ", "strip": "'ਪੂਰਣ", "add": " "},
{"match": "ਣਗੀਆਂ", "strip": "ਣਗੀਆਂ", "add": ""},
{"match": "ਸ਼ਕਤੀ", "strip": "ਸ਼ਕਤੀ", "add": " "},
{"match": "ਸ਼ੀਲਤਾ", "strip": "ਸ਼ੀਲਤਾ", "add": " "},
{"match": "ਸਤਾਨ", "strip": "ਸਤਾਨ", "add": " "},
{"match": 'ੀਕਰਨ', "strip": 'ੀਕਰਨ', "add": " "},
{"match": " ੀਕਰਨ", "strip": " ੀਕਰਨ", "add": ""},
{"match": "ਉਂਦਾ", "strip": "ਉਂਦਾ", "add": ""},
{"match": "ਉਂਦੀ", "strip": "ਉਂਦੀ", "add": ""},
{"match": "ਉਂਦੇ", "strip": "ਉਂਦੇ", "add": ""},
{"match": "ਉਣਾ", "strip": "ਉਣਾ", "add": ""},
{"match": "ਉਣੀ", "strip": "ਉਣੀ", "add": ""},
{"match": "ਉਣੇ", "strip": "ਉਣੇ", "add": ""},
{"match": "ਅਈ", "strip": "ਅਈ", "add": ""},
{"match": "ਅਣ", "strip": "ਅਣ", "add": ""},
{"match": "'ਅਤ", "strip": "'ਅਤ", "add": ""},
{"match": "ਆਈ", "strip": "ਆਈ", "add": ""},
{"match": "ਆਉ", "strip": "ਆਉ", "add": ""},
{"match": "ਆਉਂ", "strip": "ਆਉਂ", "add": ""},
{"match": "ਆਕ", "strip": "ਆਕ", "add": ""},
{"match": "ਆਣੀ", "strip": "ਆਣੀ", "add": ""},
{"match": "ਆਨੀ", "strip": "ਆਨੀ", "add": ""},
{"match": "ਆਰ", "strip": "ਆਰ", "add": ""},
{"match": "ਆਰਾ", "strip": "ਆਰਾ", "add": ""},
{"match": "ਆਰੀ", "strip": "ਆਰੀ", "add": ""},
{"match": "ਆਲ", "strip": "ਆਲ", "add": ""},
{"match": "ਆਲਾ", "strip": "ਆਲਾ", "add": ""},
{"match": "ਆਲੂ", "strip": "ਆਲੂ", "add": ""},
{"match": "ਐਲ", "strip": "ਐਲ", "add": ""},
{"match": "ਆੜੀ", "strip": "ਆੜੀ", "add": ""},
{"match": "ਇਕ", "strip": "ਇਕ", "add": ""},
{"match": "ਇਤ", "strip": "ਇਤ", "add": ""},
{"match": "ਈਆਂੀ", "strip": "ਈਆਂੀ", "add": ""},
{"match": "ਇਆ", "strip": "ਇਆ", "add": ""},
{"match": "ਇਆਂ", "strip": "ਆਂ", "add": ""}, 
{"match": "ਈਆ", "strip": "ਆ", "add": ""},
{"match": "ੲੀਆ", "strip": "ਆ", "add": ""},
{"match": "ਈਨ", "strip": "ਈਨ", "add": ""},
{"match": "ਏਟਾ", "strip": "ਏਟਾ", "add": ""},
{"match": "ਏਟੀ", "strip": "ਏਟੀ", "add": ""},
{"match": "ਏਰਾ", "strip": "ਏਰਾ", "add": ""},
{"match": "ਏਲੀ", "strip": "ਏਲੀ", "add": ""},
{"match": "ਈਲਾ", "strip": "ਈਲਾ", "add": ""},
{"match": "ਏਗਾ", "strip": "ਏਗਾ", "add": ""},
{"match": "ਏਗੀ", "strip": "ਏਗੀ", "add": ""},
{"match": "ਕਾਰ", "strip": "ਕਾਰ", "add": ""},
{"match": "ਕਾਰੀ", "strip": "ਕਾਰੀ", "add": ""},
{"match": "ਕੁਸ਼ੀ", "strip": "ਕੁਸ਼ੀ", "add": ""},
{"match": "ਖੋਰਾ", "strip": "ਖੋਰਾ", "add": ""},
{"match": "ਖ਼ੋਰ", "strip": "ਖ਼ੋਰ", "add": ""},
{"match": "ਖੋਰ", "strip": "ਖੋਰ", "add": ""},
{"match": "ਖ਼ਾਨਾ", "strip": "ਖ਼ਾਨਾ", "add": ""},
{"match": "ਗਾਰ", "strip": "ਗਾਰ", "add": ""},
{"match": "ਗਿਰੀ", "strip": "ਗਿਰੀ", "add": ""},
{"match": "ਗੀਰ", "strip": "ਗੀਰ", "add": ""},
{"match": "ਗਰ", "strip": "ਗਰ", "add": ""},
{"match": "ਗ਼ਰ", "strip": "ਗ਼ਰ", "add": ""},
{"match": "ਘਰ", "strip": "ਘਰ", "add": ""},
{"match": "ਘਾਤ", "strip": "ਘਾਤ", "add": ""},
{"match": "ਚਾਰੀ", "strip": "ਚਾਰੀ", "add": ""},
{"match": "ਤਣ", "strip": "ਤਣ", "add": ""},
{"match": "ਤਰ", "strip": "ਤਰ", "add": ""},
{"match": "ਤਾਈ", "strip": "ਤਾਈ", "add": ""},
{"match": "ਤੇਰਾ", "strip": "ਤੇਰਾ", "add": ""},
{"match": "ਦਾਨ", "strip": "ਦਾਨ", "add": ""},
{"match": "ਦਾਰ", "strip": "ਦਾਰ", "add": ""},
{"match": "ਦਾਰੀ", "strip": "ਦਾਰੀ", "add": ""},
{"match": "ਦਿਲ", "strip": "ਦਿਲ", "add": ""},
{"match": "ਧਰ", "strip": "ਧਰ", "add": ""},
{"match": "ਧਾਰ", "strip": "ਧਾਰ", "add": ""},
{"match": "ਧਾਰੀ", "strip": "ਧਾਰੀ", "add": ""},
{"match": "ਨਾਕ", "strip": "ਨਾਕ", "add": ""},
{"match": "ਪਣ", "strip": "ਪਣ", "add": ""},
{"match": "ਪਨ", "strip": "ਪਨ", "add": ""},
{"match": "ਪੁਣਾ", "strip": "ਪੁਣਾ", "add": ""},
{"match": "ਪੁੱਣਾ", "strip": "ਪੁੱਣਾ", "add": ""},
{"match": "ਪੋਸ਼", "strip": "ਪੋਸ਼", "add": ""},
{"match": "ਪੰਥੀ", "strip": "ਪੰਥੀ", "add": ""},
{"match": "ਬਾਜ਼ੀ", "strip": "ਬਾਜ਼ੀ", "add": ""},
{"match": "ਬਾਜੀ", "strip": "ਬਾਜੀ", "add": ""},
{"match": "ਬਾਨ", "strip": "ਬਾਨ", "add": ""},
{"match": "ਬਾਜ", "strip": "ਬਾਜ", "add": ""},
{"match": "ਬੱਧ", "strip": "ਬੱਧ", "add": ""},
{"match": "ਬਾਜ਼", "strip": "ਬਾਜ਼", "add": ""},
{"match": "ਮਾਨ", "strip": "ਮਾਨ", "add": ""},
{"match": "ਮਾਰ", "strip": "ਮਾਰ", "add": ""},
{"match": "ਮੁਖੀ", "strip": "ਮੁਖੀ", "add": ""},
{"match": "ਮੰਦੀ", "strip": "ਮੰਦੀ", "add": ""},
{"match": "ਮੰਦ", "strip": "ਮੰਦ", "add": ""},
{"match": "ਣਗੇ", "strip": "ਣਗੇ", "add": ""},
{"match": "ਯੋਗ", "strip": "ਯੋਗ", "add": ""},
{"match": "ਰਾਨ", "strip": "ਰਾਨ", "add": ""},
{"match": "ਵਟ", "strip": "ਵਟ", "add": ""},
{"match": "ਵਰ", "strip": "ਵਰ", "add": ""},
{"match": "ਵਾਦ", "strip": "ਵਾਦ", "add": ""},
{"match": "ਵਾਨ", "strip": "ਵਾਨ", "add": ""},
{"match": "ਵਾਲਾ", "strip": "ਵਾਲਾ", "add": ""},
{"match": "ਵਾਲ", "strip": "ਵਾਲ", "add": ""},
{"match": "ਵੰਤੀ", "strip": "ਵੰਤੀ", "add": ""},
{"match": "ਵੰਤ", "strip": "ਵੰਤ", "add": ""},
{"match": "ਵੰਦ", "strip": "ਵੰਦ", "add": ""},
{"match": "ਸ਼ਾਹੀ", "strip": "ਸ਼ਾਹੀ", "add": ""},
{"match": "ਸ਼ੀਲ", "strip": "ਸ਼ੀਲ", "add": ""},
{"match": "ਸਾਜ", "strip": "ਸਾਜ", "add": ""},
{"match": "ਸਾਜ਼", "strip": "ਸਾਜ਼", "add": ""},
{"match": "ਸਾਰ", "strip": "ਸਾਰ", "add": ""},
{"match": "ਸਾਲਾ", "strip": "ਸਾਲਾ", "add": ""},
{"match": "ਸਾਲ", "strip": "ਸਾਲ", "add": ""},
{"match": "ਹਾਰੀ", "strip": "ਹਾਰੀ", "add": ""},
{"match": "ਹਾਰਾ", "strip": "ਹਾਰਾ", "add": ""},
{"match": "ਹਾਰ", "strip": "ਹਾਰ", "add": ""},
{"match": "ਹੀਣ", "strip": "ਹੀਣ", "add": ""},
{"match": "ਹੀੋਣ", "strip": "ਹੀੋਣ", "add": ""},
{"match": "ਿਉਂ", "strip": "ਿਉਂ", "add": "ਾ"},
{"match": "ਿਓਂ", "strip": "ਿਓਂ", "add": "ੇ"},   
{"match": "ੀਓ", "strip": "ਓ", "add": ""},
{"match": "ਿਓ", "strip": "ਿਓ", "add": "ਾ/ੀ"},
{"match": "ਿੳ", "strip": "ਿੳ", "add": "ਾ/ੀ"},        
{"match": "ਊ", "strip": "ਊ", "add": ""},
{"match": "ਉ", "strip": "ਉ", "add": ""},
{"match": "ਓ", "strip": "ਓ", "add": ""},
{"match": "ੀਆਂ", "strip": "ਆਂ", "add": ""},
{"match": "ੀਆਂ", "strip": "ਆਂ", "add": ""},
{"match": "ਿਆਂ", "strip": "ਆਂ", "add": ""},
{"match": "ੀਆ", "strip": "ਆ", "add": ""},
{"match": "ਿਆ", "strip": "ਿਆ", "add": "ਾ"},
{"match": "ੂਆਂ", "strip": "ਆਂ", "add": ""},
{"match": "ਆਂ", "strip": "ਆਂ", "add": ""},
{"match": "ਆ", "strip": "ਆ", "add": ""},
{"match": " ਾਈ", "strip": " ਾਈ", "add": ""},
{"match": 'ਾਈ', "strip": 'ਾਈ', "add": ""},
{"match": "ਿਏ", "strip": "ਿਏ", "add": "ੀ"},        
{"match": "ੀਏ", "strip": "ਏ", "add": ""},
{"match": "ਈਂ", "strip": "ਈਂ", "add": ""},
{"match": "ਈ", "strip": "ਈ", "add": ""},
{"match": "ਏ", "strip": "ਏ", "add": ""},
{"match": "ਕਾ", "strip": "ਕਾ", "add": ""},
{"match": "ਕੀ", "strip": "ਕੀ", "add": ""},
{"match": "ਕ", "strip": "ਕ", "add": ""},
{"match": "ਗੀ", "strip": "ਗੀ", "add": ""},
{"match": "ੇਗਾ", "strip": "ੇਗਾ", "add": ""},
{"match": "ੇਗੀ", "strip": "ੇਗੀ", "add": ""},
{"match": "ੋਗੇ", "strip": "ੋਗੇ", "add": ""},
{"match": "ਚੀ", "strip": "ਚੀ", "add": ""},
{"match": "ਣੀ", "strip": "ਣੀ", "add": ""},
{"match": "ਣੇ", "strip": "ਣੇ", "add": ""},
{"match": "ਣਾ", "strip": "ਣਾ", "add": ""},
{"match": "ਣ", "strip": "ਣ", "add": ""},
{"match": "ਤੀ", "strip": "ਤੀ", "add": ""},
{"match": "ਤਾ", "strip": "ਤਾ", "add": ""},
{"match": "ਤ", "strip": "ਤ", "add": ""},
{"match": "ਜੀ", "strip": "ਜੀ", "add": ""},
{"match": "ੇ", "strip": "ੇ", "add": "ਾ"},
{"match": "ਾਂਦਾ", "strip": " ਂਦਾ", "add": "ਾ"},
{"match": "ਾਂਦੀ", "strip": "ਾਂਦੀ", "add": "ਾ"},
{"match": " ਾਂਦੇ", "strip": "  ਾਂਦੇ", "add": "ਾ"},
{"match": "ਦਾ", "strip": "ਦਾ", "add": ""},
{"match": "ਦੀ", "strip": "ਦੀ", "add": ""},             
{"match": "ਦੇ", "strip": "ਦੇ", "add": ""},
{"match": "ਨੀ", "strip": "ਨੀ", "add": ""},
{"match": "ਨਾ", "strip": "ਨਾ", "add": ""},
{"match": "ਨੇ", "strip": "ਨੇ", "add": ""},
{"match": "ਨਾਂ", "strip": "ਨਾਂ", "add": ""},
{"match": "ਨ", "strip": "ਨ", "add": ""},
{"match": "ਪਾ", "strip": "ਪਾ", "add": ""},
{"match": "ਪ", "strip": "ਪ", "add": ""},
{"match": 'ੀਲਾ', "strip": 'ੀਲਾ', "add": ""},
{"match": " ੀਲਾ", "strip": " ੀਲਾ", "add": ""},
{"match": 'ੂਲ਼ਾ', "strip": 'ੂਲ਼ਾ', "add": ""},
{"match": " ੂਲਾ", "strip": " ੂਲਾ", "add": ""},
{"match": " ੂਲਾ", "strip": " ੂਲਾ", "add": ""},
{"match": 'ੇਲੂ', "strip": 'ੇਲੂ', "add": ""},
{"match": "ਲੂ", "strip": "ਲੂ", "add": ""},
{"match": "ਲਾ", "strip": "ਲਾ", "add": ""},
{"match": "ਲ", "strip": "ਲ", "add": ""},
{"match": "ਵੀ", "strip": "ਵੀ", "add": ""},
{"match": "ਵਾਂ", "strip": "ਵਾਂ", "add": ""},
{"match": "ਵਾ", "strip": "ਵਾ", "add": ""},
{"match": "ਵ", "strip": "ਵ", "add": ""},
{"match": "ੜੀ", "strip": "ੜੀ", "add": ""},
{"match": "ੜਾ", "strip": "ੜਾ", "add": ""},
{"match": "ੜ", "strip": "ੜ", "add": ""},
{"match": "ਸ", "strip": "ਸ", "add": ""},
{"match": "ਜ਼", "strip": "ਜ਼", "add": ""},
{"match": "ਜ", "strip": "ਜ", "add": ""},     
{"match": " ਾ", "strip": " ਾ", "add": ""},
{"match": 'ਾ', "strip": 'ਾ', "add": ""},
{"match": "ੀਂ", "strip": "ੀਂ", "add": ""},
{"match": " ਿ", "strip": " ਿ", "add": ""},
{"match": " ੀ", "strip": " ੀ", "add": ""},
{"match": 'ਿ', "strip": 'ਿ', "add": ""},
{"match": 'ੀ', "strip": 'ੀ', "add": ""},
{"match": 'ੁ', "strip": 'ੁ', "add": ""},
{"match": 'ੂ', "strip": 'ੂ', "add": ""}, 
{"match": " ੂ", "strip": " ੂ", "add": ""},
{"match": "ਾਂ", "strip": "ਾਂ", "add": ""},
{"match": "ੋ", "strip": "ੋ", "add": ""},
{"match": "ੋਂ", "strip": "ੋਂ", "add": ""},
{"match": "ੋ ਂ", "strip": "ੋ ਂ", "add": ""}
        ]
        self.dictionary_cache = {}
        self.data_dir = data_dir
        self.pronouns = self.load_words('Punjabi_Pronouns.txt')
        self.adverbs = self.load_words('Punjabi_Adverbs.txt')
        self.postpositions = self.load_words('Punjabi_Postpositions.txt')
        self.vocabulary = self.load_words('Punjabi_Vocabulary.txt')
        self.names = self.load_words('Punjabi_Boys_Girls_Name.txt')
        self.suffix = self.load_words('Suffix.txt')

    def load_words(self, filename):
        path = os.path.join(self.data_dir, filename)
        try:
            with open(path, 'r', encoding='utf-8') as file:
                words = set(line.strip() for line in file)
            return words
        except FileNotFoundError:
            print(f"Words file '{filename}' not found. Proceeding without it.")
            return set()

    def apply_rules(self, word):
        for rule in self.rules:
            if word.endswith(rule["match"]):
                new_word = word[:-len(rule["strip"])] + rule["add"]
                return new_word
        return word

    def stem_word(self, word):
        if word in self.pronouns or word in self.adverbs or word in self.postpositions or word in self.vocabulary or word in self.names or word in self.suffix:
            return word
        return self.apply_rules(word)

    def stem_text(self, text):
        words = text.split()
        stemmed_words = [self.stem_word(word) for word in words]
        return ' '.join(stemmed_words)
